# -*- coding: utf-8 -*-
"""salir-csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqfQdPgvgqg2ITf_LijzcYTZtD6hrw6o
"""

import csv

# ---------------------------------------------------------
# FUNCIÓN PARA EXPORTAR LOS DATOS A CSV
# ---------------------------------------------------------
def exportar_csv(clientes, totales):
    nombre_archivo = "reporte_final_del_dia.csv"

    with open(nombre_archivo, mode="w", newline="") as archivo:
        escritor = csv.writer(archivo)

        # Sección de clientes
        escritor.writerow(["CLIENTES REGISTRADOS"])
        escritor.writerow(["Nombre", "Documento", "Habitación"])

        for c in clientes:
            escritor.writerow([c["nombre"], c["documento"], c["habitacion"]])

        escritor.writerow([])  # línea vacía
        escritor.writerow(["RESULTADOS DEL ADMINISTRADOR"])
        escritor.writerow(["Costos", "Ventas", "Ganancias"])
        escritor.writerow([totales["costos"], totales["ventas"], totales["ganancias"]])

    print(f"\nArchivo CSV exportado correctamente como: {nombre_archivo}")


# ---------------------------------------------------------
# FUNCIÓN PARA SALIR DE MANERA SEGURA
# ---------------------------------------------------------
def salir_sistema():
    print("\n=== FIN DEL DÍA ===")

    opcion = input("¿Desea exportar los datos del día en un archivo CSV? (si/no): ").lower()

    if opcion == "si":
        exportar_csv(clientes_registrados, totales)

    print("\nEl sistema se ha cerrado de manera segura. ¡Hasta mañana!")


# ---------------------------------------------------------
# MENÚ PRINCIPAL SIMPLIFICADO
# ---------------------------------------------------------
print("=== SISTEMA ARENA AZUL ===")

while True:
    print("\nOpciones:")
    print("1. Registrar clientes / servicios")
    print("2. Ver reportes")
    print("3. Salir del sistema")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        print("\nAquí iría el código para registrar clientes...")

    elif opcion == "2":
        print("\nAquí iría el código para mostrar reportes...")

    elif opcion == "3":
        salir_sistema()
        break  # Sale del ciclo principal y apaga el sistema

    else:
        print("Opción inválida, intente de nuevo.")